// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:goal/src/models/goal_entry.dart';
import 'package:goal/src/models/goal_meta.dart';
import 'package:goal/src/models/goal_note.dart';
import 'package:goal/src/models/goal_priority.dart';
import 'package:goal/src/models/goal_status.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GoalEntryAdapter());
    registerAdapter(GoalMetaAdapter());
    registerAdapter(GoalNoteAdapter());
    registerAdapter(GoalPriorityAdapter());
    registerAdapter(GoalStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GoalEntryAdapter());
    registerAdapter(GoalMetaAdapter());
    registerAdapter(GoalNoteAdapter());
    registerAdapter(GoalPriorityAdapter());
    registerAdapter(GoalStatusAdapter());
  }
}
